language: python
python:
  - '3.7'

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="website.settings.travis"

services:
  - postgresql

script:
  - coverage run manage.py test

branches:
  only:
    - staging


