language: python
python:
  - '3.7'

before_script:
  - pip install -r requirements.txt
  - wget https://chromedriver.storage.googleapis.com/86.0.4240.22/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.7.1/bin
  - export CHROME_BIN=chromium-browser

env: DJANGO_SETTINGS_MODULE="website.settings.travis"

services:
  - postgresql

script:
  - coverage run manage.py test

branches:
  only:
    - staging
    - 'p11'

addons:
  chrome: stable

sudo: required
