# Generated by Django 3.0.7 on 2020-07-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre', '0002_auto_20200713_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_favorite',
            field=models.BooleanField(null=True),
        ),
    ]
