# Generated by Django 3.0.7 on 2020-08-06 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre', '0005_auto_20200806_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='favorites',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(help_text='Name of the category', max_length=75, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(help_text='Foreign key to the category of the product', on_delete=django.db.models.deletion.CASCADE, to='purbeurre.Categories', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.URLField(help_text='Hyperlink to Openfoodfacts product image', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='products',
            name='link',
            field=models.URLField(help_text='Hyperlink to Openfoodfacts product page', verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(help_text='Product name', max_length=75, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='products',
            name='nutriscore',
            field=models.CharField(help_text='Nutritional score of the product', max_length=1, null=True, verbose_name='Nutriscore'),
        ),
        migrations.AlterField(
            model_name='products',
            name='nutrition_image',
            field=models.URLField(help_text='Hyperlink to Openfoodfacts ranking nutriscore image', verbose_name='Nutrition image'),
        ),
    ]
